# aliases.R

# --- Define Immune Cell Aliases for Extraction ---
immune_cell_alias_list <- list(
  "T cell" = c("T cell", "T cells", "T-cell", "T-cells", "T lymphocyte", "T lymphocytes"),
  "CD4+ T cell" = c("CD4+ T cell", "CD4+ T cells", "CD4+ T-cell", "CD4+ T-cells", "helper T cell", "helper T cells", "Th cell", "Th cells"),
  "CD8+ T cell" = c("CD8+ T cell", "CD8+ T cells", "CD8+ T-cell", "CD8+ T-cells", "cytotoxic T cell", "cytotoxic T cells", "CTL", "CTLs"),
  "Regulatory T cell" = c("regulatory T cell", "regulatory T cells", "Treg", "Tregs"),
  "B cell" = c("B cell", "B cells", "B-cell", "B-cells", "B lymphocyte", "B lymphocytes"),
  "Natural killer cell" = c("natural killer cell", "natural killer cells", "NK cell", "NK cells"),
  "Monocyte" = c("monocyte", "monocytes"),
  "Macrophage" = c("macrophage", "macrophages"),
  "Dendritic cell" = c("dendritic cell", "dendritic cells", "DC", "DCs"),
  "Neutrophil" = c("neutrophil", "neutrophils"),
  "Eosinophil" = c("eosinophil", "eosinophils"),
  "Basophil" = c("basophil", "basophils"),
  "Mast cell" = c("mast cell", "mast cells"),
  "Innate lymphoid cell" = c("innate lymphoid cell", "innate lymphoid cells", "ILC", "ILCs"),
  "ILC1" = c("ILC1"),
  "ILC2" = c("ILC2"),
  "ILC3" = c("ILC3"),
  "Plasma cell" = c("plasma cell", "plasma cells"),
  "Memory T cell" = c("memory T cell", "memory T cells"),
  "Effector T cell" = c("effector T cell", "effector T cells"),
  "Naive T cell" = c("naive T cell", "naive T cells"),
  "Exhausted T cell" = c("exhausted T cell", "exhausted T cells"),
  "Memory B cell" = c("memory B cell", "memory B cells"),
  "Hematopoietic stem cell" = c("hematopoietic stem cell", "hematopoietic stem cells")
)

# --- Define Virus Aliases for Extraction ---
virus_alias_expanded <- list(
  "Adeno-Associated Virus" = c("adeno-associated virus", "AAV", "AAVs", "rAAV", "scAAV", "adeno-associated dependoparvovirus a", "adeno-associated dependoparvovirus b"),
  "Vesicular Stomatitis Virus" = c("vesicular stomatitis virus", "VSV"),
  "Newcastle Disease Virus" = c("newcastle disease virus", "NDV"),
  "Seneca Valley Virus" = c("seneca valley virus", "SVV"),
  "Myxoma Virus" = c("myxoma virus", "MYXV"),
  "ECHO-7 virus" = c("ECHO-7 virus", "Rigvir", "Riga virus"),
  "Maraba Virus" = c("maraba virus"),
  "Semliki Forest virus" = c("Semliki Forest virus", "SFV"),
  "Sindbis virus" = c("Sindbis virus", "SINV"),
  "Venezuelan equine encephalitis virus" = c("Venezuelan equine encephalitis virus", "VEEV"),
  "West Nile Virus" = c("West Nile Virus", "WNV"),
  "Simian virus 40" = c("Simian virus 40", "SV40"),
  "Rabies Virus" = c("Rabies Virus"),
  "Human Immunodeficiency Virus" = c("human immunodeficiency virus", "HIV", "HIV-1"),
  "Herpes Simplex Virus" = c("talimogene laherparepvec", "TVEC", "T-VEC", "herpes simplex virus type 1", "HSV-1", "HSV1", "oHSV", "herpes simplex virus", "HSVs", "HSV", "herpes"),
  "Herpes Simplex Virus 2" = c("HSV-2", "HSV2"),
  "Vaccinia Virus" = c("vaccinia virus", "VV", "VACV"),
  "Measles Virus" = c("measles virus", "MV", "rubeola"),
  "Lentivirus" = c("lentivirus", "LVs", "LV", "LVV", "lentiviral vectors"),
  "Retrovirus" = c("retrovirus", "RVs", "RV", "retroviral vectors", "gamma-retroviruses"),
  "Adenovirus" = c("adenovirus", "Ads", "Ad", "AV", "adenoviruses", "hAdV", "HAdV-5"),
  "Reovirus" = c("reovirus"),
  "Poliovirus" = c("poliovirus"),
  "Coxsackievirus" = c("coxsackievirus", "CV"),
  "Parvovirus" = c("parvovirus", "rat parvovirus H-1PV"),
  "Baculovirus" = c("baculovirus"),
  "Foamy Virus" = c("foamy virus", "FVV", "spumavirus"),
  "Alphavirus" = c("alphavirus"),
  "Flavivirus" = c("flavivirus"),
  "Polyomavirus" = c("polyomavirus"),
  "Rhabdovirus" = c("rhabdovirus")
)